### ISSUE TITLE
Auto update version numbers

### ISSUE THREAD

**Issue by sernaferna** [sernaferna/ds-wireframes#146]
Thinking this should happen on PR approval. [This tool](https://github.com/marketplace/actions/automated-version-bump) might be the best option.

From the GH Actions docs:

**Running your workflow when a pull request merges**
When a pull request merges, the pull request is automatically closed. To run a workflow when a pull request merges, use the `pull_request` `closed` event type along with a conditional that checks the `merged` value of the event. For example, the following workflow will run whenever a pull request closes. The `if_merged` job will only run if the pull request was also merged.

```YAML
on:
  pull_request:
    types:
      - closed
    paths:
      - 'apps/ds-api/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```
